name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fwilhe2/automatic-computing-machine@main
      with:
        milliseconds: 100

    - uses: fwilhe2/bump-version@step-summary
      id: bump
    - run: echo ${{ steps.bump.outputs.newVersion }}

    - uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.bump.outputs.newVersion }}
